.nh
.TH "GH-GIST-EDIT" "1" "Dec 2021" "GitHub CLI 2.4.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-edit - Edit one of your gists


.SH SYNOPSIS
.PP
\fB\fCgh gist edit {<id> | <url>} [flags]\fR


.SH OPTIONS
.TP
\fB\fC-a\fR, \fB\fC--add\fR \fB\fC<string>\fR
Add a new file to the gist

.TP
\fB\fC-f\fR, \fB\fC--filename\fR \fB\fC<string>\fR
Select a file to edit


.SH SEE ALSO
.PP
\fB\fCgh-gist(1)\fR
