# inside .github/workflows/your-action.yml
name: Upload file to bucket
on: 
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
   # - uses: actions/checkout@master
   # - uses: RSK14/Devops-@s3
    - uses: RSK14/Devops-@S3
      
      with:
       args: --acl Private-read --follow-symlinks --delete
      env:
       FILE: git1
       
       AWS_REGION: '*'   # optional: defaults to us-east-1
       S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       SOURCE_DIR: "public"
