# inside .github/workflows/your-action.yml
name: Add File to Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Upload file to bucket
      uses: RSK14/Devops-@master
      with:
       args: --acl public-read
      env:
       FILE: ./test.txt
       AWS_REGION: 'ap-south-1'
       S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ AKIAROL3D3EXCINAPC4I }}
       AWS_SECRET_ACCESS_KEY: ${{ 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 }}
       SOURCE_DIR: "depoly"
