# inside .github/workflows/your-action.yml
name: Add File to Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Upload file to bucket
      uses: RSK14/Devops-@master
      with:
       args: --acl public-read
      
      env:
       FILE: test
       
       AWS_REGION: '*'
       S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       SOURCE_DIR: "deploy"
 
