# inside .github/workflows/your-action.yml
name: Add File to Bucket
on:
  pull_request:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Upload file to bucket
      uses: RSK14/Devops-@master
      with:
       args: --acl public-read --delete
    - name: Install
      run: npm cache clean --force
      
    - name: Install
      run: npm install 

    - name: ng  
      run: ng build --prod

    env:
       FILE: test30
       AWS_REGION: 'us-east-1'
       S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       SOURCE_DIR: "deploy"
